load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "pantoken_tar_validate_lib",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    crate_name = "pantoken_tar_validate",
    edition = "2024",
    deps = [
        "@crates//flate2",
        "@crates//tar",
    ],
    visibility = ["//visibility:public"],
)

rust_binary(
    name = "pantoken_tar_validate",
    srcs = ["src/main.rs"],
    edition = "2024",
    deps = [":pantoken_tar_validate_lib"],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "unit_tests",
    crate = ":pantoken_tar_validate_lib",
)
