//! Shared fold conformance corpus — Rust side.
//!
//! Reads JSON fixture files from `tests/fold-corpus/`, folds each event
//! sequence via `fold_all`, and asserts the result matches the `expected`
//! field in the file. The `expected` values are generated by Rust (the
//! oracle) via `UPDATE_FOLD_CORPUS=1`.
//!
//! The TS test `protocol/src/state.corpus.test.ts` reads the same files and
//! validates `foldAll` produces identical output — proving both implementations
//! agree.

use std::fs;
use std::path::PathBuf;

use pantoken_protocol::session_driver::SessionDriverEvent;
use pantoken_protocol::state::fold_all;
use serde_json::Value;

struct CorpusCase {
    name: String,
    events: Vec<Value>,
    expected: Value,
}

fn corpus_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("PANTOKEN_FOLD_CORPUS_DIR") {
        return PathBuf::from(dir);
    }
    // Test runner env: PANTOKEN_FOLD_CORPUS_FILES contains space-separated file paths.
    // Derive the corpus directory from the first file's parent.
    if let Ok(files) = std::env::var("PANTOKEN_FOLD_CORPUS_FILES") {
        if let Some(first) = files.split_whitespace().next() {
            if let Some(parent) = PathBuf::from(first).parent() {
                return parent.to_path_buf();
            }
        }
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fold-corpus")
}

fn load_cases() -> Vec<CorpusCase> {
    let mut cases = Vec::new();
    for entry in fs::read_dir(corpus_dir()).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let raw =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path:?}: {e}"));
        let json: Value =
            serde_json::from_str(&raw).unwrap_or_else(|e| panic!("failed to parse {path:?}: {e}"));
        cases.push(CorpusCase {
            name: json["name"]
                .as_str()
                .unwrap_or_else(|| panic!("corpus case {path:?} has no 'name'"))
                .to_string(),
            events: json["events"]
                .as_array()
                .unwrap_or_else(|| panic!("corpus case '{}' has no 'events' array", json["name"]))
                .clone(),
            expected: json["expected"].clone(),
        });
    }
    // Sort by name for deterministic test output.
    cases.sort_by(|a, b| a.name.cmp(&b.name));
    cases
}

#[test]
fn fold_corpus_case_count() {
    let cases = load_cases();
    assert!(
        cases.len() >= 18,
        "expected ≥18 corpus cases, found {}",
        cases.len()
    );
    for case in &cases {
        assert!(!case.name.is_empty(), "corpus case has empty name");
        // Empty events is valid (the `empty` case), but then expected must have
        // empty items.
        assert!(
            !case.events.is_empty()
                || case.expected["items"]
                    .as_array()
                    .is_some_and(|a| a.is_empty()),
            "corpus case '{}' has empty events but non-empty items",
            case.name
        );
    }
}

#[test]
fn fold_corpus_conformance() {
    for case in load_cases() {
        let events: Vec<SessionDriverEvent> = case
            .events
            .iter()
            .map(|v| {
                serde_json::from_value(v.clone()).unwrap_or_else(|e| {
                    panic!("failed to deserialize event in case '{}': {e}", case.name)
                })
            })
            .collect();
        let state = fold_all(&events);
        let actual = serde_json::to_value(&state).unwrap();
        assert_eq!(
            actual, case.expected,
            "corpus case '{}' mismatch",
            case.name
        );
    }
}

#[test]
fn fold_corpus_update_golden() {
    if std::env::var("UPDATE_FOLD_CORPUS").is_err() {
        return;
    }
    for entry in fs::read_dir(corpus_dir()).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let mut json: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
        let events: Vec<SessionDriverEvent> = json["events"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| serde_json::from_value(v.clone()).unwrap())
            .collect();
        let state = fold_all(&events);
        json["expected"] = serde_json::to_value(&state).unwrap();
        fs::write(&path, serde_json::to_string_pretty(&json).unwrap() + "\n").unwrap();
    }
}
