exports_files(["path-stability.sh", "validate-archive.sh"])

filegroup(
    name = "path_stability_py",
    srcs = ["path-stability.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "path_stability_fixture",
    srcs = glob(["path-stability-fixtures/**"]),
    visibility = ["//visibility:public"],
)
