load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "pantoken_remote_layout",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//server-rs/pantoken-protocol:pantoken_protocol",
        "@crates//serde",
    ],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "unit_tests",
    crate = ":pantoken_remote_layout",
)
